import io
from uuid import uuid4
from xml.sax.saxutils import escape

from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer

from app.agents.logging import log_agent_failure, log_agent_start, log_agent_success
from app.agents.models import _extract_usage, content_text, get_model
from app.agents.state import AgentState
from app.core import storage

PDF_SYSTEM_PROMPT = """You are a document writer. Produce well-structured plain-text content about the user's topic: a title on the first line, followed by sections separated by blank lines. Do NOT use markdown symbols (no #, *, -, **). Use only plain paragraphs."""


async def pdf_node(state: AgentState) -> dict:
    t0 = log_agent_start("pdf", state)
    try:
        result = await get_model("chat").ainvoke(
            [
                ("system", PDF_SYSTEM_PROMPT),
                ("human", state["prompt"]),
            ]
        )
        content = content_text(result.content).strip()
        usage = _extract_usage(result)

        styles = getSampleStyleSheet()
        flowables = []
        paragraphs = [p.strip() for p in content.split("\n\n") if p.strip()]
        for i, para in enumerate(paragraphs):
            style = styles["Title"] if i == 0 else styles["BodyText"]
            flowables.append(Paragraph(escape(para.replace("\n", " ")), style))
            flowables.append(Spacer(1, 12))

        flowables.append(Spacer(1, 24))
        flowables.append(Paragraph("Generated by Cortex AI", styles["Italic"]))

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter)
        doc.build(flowables)
        pdf_bytes = buffer.getvalue()

        filename = f"{uuid4().hex}.pdf"
        url = storage.save_file(filename, pdf_bytes)

        log_agent_success("pdf", state, t0, pdf_url=url, paragraphs=len(paragraphs))
        return {
            "ai_response": f"Your PDF is ready: [Download PDF]({url})",
            "images": [],
            "token_usage": usage,
        }
    except Exception as exc:
        log_agent_failure("pdf", state, exc)
        raise
