import json
from io import BytesIO
from uuid import uuid4

from pptx import Presentation
from pptx.util import Inches, Pt

from app.agents.logging import log_agent_failure, log_agent_start, log_agent_success
from app.agents.models import _extract_usage, content_text, get_model
from app.agents.state import AgentState
from app.core import storage

PPT_SYSTEM_PROMPT = """You are a presentation designer. Return ONLY a JSON object, with no markdown fences or extra text, in this exact shape:
{"title": "Presentation Title", "slides": [{"heading": "Slide Heading", "bullets": ["point 1", "point 2"]}]}
Include 5-7 slides total. Each slide has 3-5 concise bullets."""

TITLE_ONLY_LAYOUT = 6  # blank layout: we place our own text boxes
TITLE_CONTENT_LAYOUT = 1  # layout with a title placeholder + content placeholder


async def ppt_node(state: AgentState) -> dict:
    t0 = log_agent_start("ppt", state)
    try:
        result = await get_model("chat").ainvoke(
            [
                ("system", PPT_SYSTEM_PROMPT),
                ("human", state["prompt"]),
            ]
        )
        raw = content_text(result.content).strip()
        usage = _extract_usage(result)
        data = json.loads(raw)

        prs = Presentation()
        prs.slide_width = Inches(13.333)
        prs.slide_height = Inches(7.5)

        # Title slide
        title_slide = prs.slides.add_slide(prs.slide_layouts[TITLE_ONLY_LAYOUT])
        title_box = title_slide.shapes.add_textbox(
            Inches(1), Inches(2.5), Inches(11.333), Inches(1.5)
        )
        title_box.text_frame.text = data["title"]
        for paragraph in title_box.text_frame.paragraphs:
            paragraph.font.size = Pt(40)
            paragraph.font.bold = True

        # Content slides
        for slide_data in data["slides"]:
            slide = prs.slides.add_slide(prs.slide_layouts[TITLE_CONTENT_LAYOUT])
            slide.shapes.title.text = slide_data["heading"]
            body = slide.placeholders[1].text_frame
            for i, bullet in enumerate(slide_data["bullets"]):
                if i == 0:
                    body.text = bullet
                else:
                    p = body.add_paragraph()
                    p.text = bullet
                body.paragraphs[i].font.size = Pt(18)

        # Footer slide
        footer_slide = prs.slides.add_slide(prs.slide_layouts[TITLE_ONLY_LAYOUT])
        footer_box = footer_slide.shapes.add_textbox(
            Inches(1), Inches(6.5), Inches(11.333), Inches(0.75)
        )
        footer_box.text_frame.text = "Generated by Cortex AI"
        for paragraph in footer_box.text_frame.paragraphs:
            paragraph.font.size = Pt(14)
            paragraph.font.italic = True

        buffer = BytesIO()
        prs.save(buffer)
        ppt_bytes = buffer.getvalue()

        filename = f"{uuid4().hex}.pptx"
        url = storage.save_file(filename, ppt_bytes)

        log_agent_success("ppt", state, t0, ppt_url=url, slides=len(data["slides"]) + 2)
        return {
            "ai_response": f"Your PowerPoint is ready: [Download PPTX]({url})",
            "images": [],
            "token_usage": usage,
        }
    except Exception as exc:
        log_agent_failure("ppt", state, exc)
        raise
